name: publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Convert to HTML
        - uses: docker://pandoc/core:2.9
          with:
            args: |>
              -r gfm 
              --template=ihe_template 
              --metadata title="HIE-Whitepaper" 
              -w html 
              -o docs/index.html 
              README.md
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Publish to HTML" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
